### ISSUE TITLE
Path filter does not work

### ISSUE THREAD

**Issue by uschwarz** [collective/plone.app.changeownership#1]
```
if path:
    query['path'] = self.context.portal_url.getPortalObject().getId() + path
```

will only work if all your sites are in Data.fs, if at all, and not if you have additional mount points. Should probably be along the lines of

```
if path:
    query['path'] = '/'.join(self.context.portal_url.getPortalObject().getPhysicalPath()) + path
```

**Comment by keul** [comment]
@uschwarz totally agree. Can you provide a pull request for this change?

**Comment by malthe** [comment]
Fixed and merged.
